// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dbac35785ed561c428f6925098e216fa_2cf16a5709774485b79cc4f78dff9678 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dbac35785ed561c428f6925098e216fa_86fb5ba172214c2381975ed623c12196 : FloatBinding
    {   
        private global::GGJGame.GameState CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GGJGame.GameState)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dbac35785ed561c428f6925098e216fa_3788241317174555150);
        public override string CoherenceComponentName => "_dbac35785ed561c428f6925098e216fa_3788241317174555150";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.airStolen); }
            set { CastedUnityComponent.airStolen = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent).airStolen;

            var simFrame = ((_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent).airStolenSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.airStolen = Value;
            }
            else
            {
                update.airStolen = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.airStolenSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dbac35785ed561c428f6925098e216fa_3788241317174555150();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dbac35785ed561c428f6925098e216fa_0e8e1ddd319e4f47884119365ed268f8 : FloatBinding
    {   
        private global::GGJGame.GameState CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GGJGame.GameState)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dbac35785ed561c428f6925098e216fa_3788241317174555150);
        public override string CoherenceComponentName => "_dbac35785ed561c428f6925098e216fa_3788241317174555150";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.remainingTime); }
            set { CastedUnityComponent.remainingTime = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent).remainingTime;

            var simFrame = ((_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent).remainingTimeSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.remainingTime = Value;
            }
            else
            {
                update.remainingTime = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.remainingTimeSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dbac35785ed561c428f6925098e216fa_3788241317174555150();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dbac35785ed561c428f6925098e216fa_194945dfbf314824a5fd3dc8eeb3abc4 : BoolBinding
    {   
        private global::GGJGame.GameState CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GGJGame.GameState)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dbac35785ed561c428f6925098e216fa_3788241317174555150);
        public override string CoherenceComponentName => "_dbac35785ed561c428f6925098e216fa_3788241317174555150";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.inGame); }
            set { CastedUnityComponent.inGame = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent).inGame;

            var simFrame = ((_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent).inGameSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dbac35785ed561c428f6925098e216fa_3788241317174555150)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.inGame = Value;
            }
            else
            {
                update.inGame = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.inGameSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dbac35785ed561c428f6925098e216fa_3788241317174555150();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_dbac35785ed561c428f6925098e216fa : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_dbac35785ed561c428f6925098e216fa>();
        
        private global::GGJGame.GameState _dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["2cf16a5709774485b79cc4f78dff9678"] = new Binding_dbac35785ed561c428f6925098e216fa_2cf16a5709774485b79cc4f78dff9678(),
            ["86fb5ba172214c2381975ed623c12196"] = new Binding_dbac35785ed561c428f6925098e216fa_86fb5ba172214c2381975ed623c12196(),
            ["0e8e1ddd319e4f47884119365ed268f8"] = new Binding_dbac35785ed561c428f6925098e216fa_0e8e1ddd319e4f47884119365ed268f8(),
            ["194945dfbf314824a5fd3dc8eeb3abc4"] = new Binding_dbac35785ed561c428f6925098e216fa_194945dfbf314824a5fd3dc8eeb3abc4(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_dbac35785ed561c428f6925098e216fa()
        {
            bakedCommandBindings.Add("620044fc95cf41068d8e01ab01bd2658", BakeCommandBinding__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658_CommandTarget = (global::GGJGame.GameState)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("GGJGame.GameState.SetGameForStart", "()", SendCommand__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658, ReceiveLocalCommand__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658, MessageTarget.AuthorityOnly, _dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658_CommandTarget, false);
        }
        
        private void SendCommand__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658(MessageTarget target, object[] args)
        {
            var command = new _dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658();
            
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658(MessageTarget target, object[] args)
        {
            var command = new _dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658();
            
            
            ReceiveCommand__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658(command);
        }

        private void ReceiveCommand__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658(_dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658 command)
        {
            var target = _dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658_CommandTarget;
            
            target.SetGameForStart();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658 castedCommand:
                    ReceiveCommand__dbac35785ed561c428f6925098e216fa_620044fc95cf41068d8e01ab01bd2658(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSync_dbac35785ed561c428f6925098e216fa Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_dbac35785ed561c428f6925098e216fa>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}